name: s3 & pinecone sync

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: gptcotts-action
      uses: tomcotter7/gptcotts-github-action@main
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DIR: 'tcotts'
        PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY }}
        PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        PINECONE_NAMESPACE: ${{ secrets.PINECONE_NAMESPACE }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        
