name: s3 & pinecone sync

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
          files: |
             **.md
  
    
      
    - name: gptcotts-action
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: tomcotter7/gptcotts-github-action@latest
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DIR: 'tcotts'
        PINECONE_API_KEY: ${{secrets.PINECONE_API_KEY }}
        PINECONE_INDEX: ${{ secrets.PINECONE_INDEX }}
        PINECONE_NAMESPACE: ${{ secrets.PINECONE_NAMESPACE }}
        COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
        CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        
