# This is a basic workflow to help you get started with Actions

name: S3 sync

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: custom local action
      uses: tomcotter7/gptcotts-github-action@main
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DIR: 'tcotts'
      
    - name: Get last workflow run commit
      id: last_run
      run: |
          last_run_sha=$(git rev-list -n 1 --before="$(date -d 'last run' '+%Y-%m-%d %H:%M:%S')" main)
          echo "::set-output name=sha::$last_run_sha"

    - name: Get changed files
      id: changed_files
      run: |
          if [ -z "${{ steps.last_run.outputs.sha }}" ]; then
            # If this is the first run, get all files
            changed_files=$(git ls-tree -r --name-only HEAD)
          else
            # Get files changed since last run
            changed_files=$(git diff --name-only ${{ steps.last_run.outputs.sha }} HEAD)
          fi
          echo "Changed files:"
          echo "$changed_files"
          echo "::set-output name=files::$changed_files"

    - name: Process changed files
      run: |
          # Here you can add any processing you want to do with the changed files
          echo "Processing changed files..."
          echo "${{ steps.changed_files.outputs.files }}"
